version: "3.8"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
    volumes:
    - ./postgres:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - 8080:8080
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
